namespace SecurityOps.Domain.Entities.Community;

/// <summary>
/// A society knowledge-base entry — bylaws, FAQ, emergency contacts, etc.
/// Retrieved at query time via Postgres full-text search (tsvector column
/// is generated by the DB, so this entity doesn't model it directly).
/// </summary>
public class SocietyDoc
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public string Title { get; set; } = string.Empty;
    public string Category { get; set; } = "general";
    public string Content { get; set; } = string.Empty;
    public string[]? Tags { get; set; }
    public bool IsActive { get; set; } = true;
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;
}
